#!/bin/sh

updir=$(dirname "$1")
touch -r "$updir" /tmp/unarj-$$
dir="${1%.*}"
mkdir "$dir"
cd "$dir"
arj x -y "$OLDPWD/$1"
touch -r "$OLDPWD/$1" .
cd -
rm "$1"
touch -r /tmp/unarj-$$ "$updir"
rm -f /tmp/unarj-$$
