#!/bin/sh

dir=$(dirname "$1")
touch -r "$dir" /tmp/unarj-$$
dir="${1%.*}"
mkdir "$dir"
cd "$dir"
arj e "$OLDPWD/$1"
touch -r "$OLDPWD/$1" .
cd -
rm "$1"
touch -r /tmp/unarj-$$ "$dir"
rm -f /tmp/unarj-$$
